In [4]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [5]:
df=pd.read_csv('train.csv')

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

<h3>Selecting features that are needed</h3>

In [7]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [8]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

<h3>Preprocessing Data</h3>

In [9]:
#training dataset
x=df.drop(['Survived'],axis=1)
y=df['Survived']
x_train,x_test,y_train,y_test=train_test_split(x,
                                               y,
                                               test_size=0.2,
                                               random_state=42)

In [10]:
x_train

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
331       1    male  45.5      0      0   28.5000        S
733       2    male  23.0      0      0   13.0000        S
382       3    male  32.0      0      0    7.9250        S
704       3    male  26.0      1      0    7.8542        S
813       3  female   6.0      4      2   31.2750        S
..      ...     ...   ...    ...    ...       ...      ...
106       3  female  21.0      0      0    7.6500        S
270       1    male   NaN      0      0   31.0000        S
860       3    male  41.0      2      0   14.1083        S
435       1  female  14.0      1      2  120.0000        S
102       1    male  21.0      0      1   77.2875        S

[712 rows x 7 columns]

In [11]:
x_train.shape

(712, 7)

In [12]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [13]:
#applying imputation for missing values
si_age=SimpleImputer()
si_embarked=SimpleImputer(strategy='most_frequent')

x_train_age=si_age.fit_transform(x_train[['Age']])
x_train_embarked=si_embarked.fit_transform(x_train[['Embarked']])

x_test_age=si_age.transform(x_test[['Age']])
x_test_embarked=si_embarked.transform(x_test[['Embarked']])

In [14]:
#ohe sex and embarked
ohe_sex=OneHotEncoder(handle_unknown='ignore',sparse_output=False)
ohe_embarked=OneHotEncoder(handle_unknown='ignore',sparse_output=False)
#as we are using Decison Trees and thats why we dont need to worry about multicollinearity.

x_train_sex=ohe_sex.fit_transform(x_train[['Sex']])
x_train_embarked=ohe_embarked.fit_transform(x_train_embarked)

x_test_sex=ohe_sex.transform(x_test[['Sex']])
x_test_embarked=ohe_embarked.transform(x_test_embarked)

In [15]:
#extracting the remaining data
x_train_rem=x_train.drop(['Sex','Age','Embarked'],axis=1)
x_test_rem=x_test.drop(['Sex','Age','Embarked'],axis=1)

In [16]:
#concatenating all of it
x_train_transformed=np.concatenate((x_train_rem,x_train_sex,x_train_age,x_train_embarked),axis=1)
x_test_transformed=np.concatenate((x_test_rem,x_test_sex,x_test_age,x_test_embarked),axis=1)

In [17]:
x_test_transformed.shape

(179, 10)

<h1>APPLYING DECISION TREE ALGO</h1>

In [18]:
clf=DecisionTreeClassifier()
clf.fit(x_train_transformed,y_train)
y_pred=clf.predict(x_test_transformed)

In [19]:
y_pred

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1])

<h1>Finding Accuracy</h1>

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7821229050279329

<h1>Dumping using pickle</h1>

<p>pickle.dump() is used to save trained machine learning models or preprocessing objects into files so they can be reused later without training again.

pickle.dump() serializes and saves trained ML objects into files so they can be loaded and reused later without retraining.</p>

In [21]:
import pickle

In [22]:
pickle.dump(ohe_sex,open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('models/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('models/clf.pkl','wb'))

In [28]:
df[df['Age']==31.0]

     Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
18          0       3  female  31.0      1      0   18.0000        S
215         1       1  female  31.0      1      0  113.2750        C
318         1       1  female  31.0      0      2  164.8667        S
328         1       3  female  31.0      1      1   20.5250        S
396         0       3  female  31.0      0      0    7.8542        S
439         0       2    male  31.0      0      0   10.5000        S
637         0       2    male  31.0      1      1   26.2500        S
671         0       1    male  31.0      1      0   52.0000        S
673         1       2    male  31.0      0      0   13.0000        S
690         1       1    male  31.0      1      0   57.0000        S
744         1       3    male  31.0      0      0    7.9250        S
749         0       3    male  31.0      0      0    7.7500        Q
797         1       3  female  31.0      0      0    8.6833        S
801         1       2  female  31.0      1      1   26.2500        S
805         0       3    male  31.0      0      0    7.7750        S
817         0       2    male  31.0      1      1   37.0042        C
867         0       1    male  31.0      0      0   50.4958        S