In [17]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.compose import ColumnTransformer

In [18]:
df = pd.read_csv('train.csv')[['Age','Fare','SibSp','Parch','Survived']]
df.dropna(inplace=True)

In [19]:
df.head()

    Age     Fare  SibSp  Parch  Survived
0  22.0   7.2500      1      0         0
1  38.0  71.2833      1      0         1
2  26.0   7.9250      0      0         1
3  35.0  53.1000      1      0         1
4  35.0   8.0500      0      0         0

In [20]:
df['Family'] = df['SibSp'] + df['Parch']
df.drop(columns=['SibSp','Parch'],inplace=True)

In [21]:
df.head()

    Age     Fare  Survived  Family
0  22.0   7.2500         0       1
1  38.0  71.2833         1       1
2  26.0   7.9250         1       0
3  35.0  53.1000         1       1
4  35.0   8.0500         0       0

In [22]:
x=df.drop(['Survived'],axis=1)
y=df['Survived']

x_train,x_test,y_train,y_test=train_test_split(x,
                                               y,
                                               test_size=0.2,
                                               random_state=42)

In [23]:
x_train.shape

(571, 3)

In [24]:
y_train.shape

(571,)

In [25]:
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
accuracy_score(y_test,y_pred)

0.6223776223776224

In [26]:
cross_val_score(clf,x,y,cv=10,scoring='accuracy').mean()

np.float64(0.6485524256651017)

<h1>Applying Binarization</h1>

In [27]:
from sklearn.preprocessing import Binarizer

In [31]:
trf=ColumnTransformer([('bin',Binarizer(copy=False),['Family'])],remainder='passthrough')
#copy=False changes the Family column itself into binary values

In [32]:
x_train_trf=trf.fit_transform(x_train)
x_test_trf=trf.transform(x_test)

In [34]:
pd.DataFrame(x_train_trf,columns=['Family','Age','Fare'])

     Family   Age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]

In [36]:
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)
y_pred2=clf.predict(x_test)
accuracy_score(y_test,y_pred2)

0.6293706293706294

In [39]:
x_trf=trf.fit_transform(x)
cross_val_score(clf,x_trf,y,cv=10,scoring='accuracy').mean()

np.float64(0.630399061032864)